//Variables para inicio de sesion
export const COMENZAR_INICIO_LOGIN = "COMENZAR_INICIO_LOGIN";
export const INICIAR_SESION_EXITO = "INICIAR_SESION_EXITO";
export const INICIAR_SESION_ERROR = "INICIAR_SESION_ERROR";
//Consulta datos usuarios
export const COMENZAR_DESCARGA_USUARIOS = "COMENZAR_DESCARGA_USUARIOS";
export const DESCARGAR_USUARIOS_EXITO = "DESCARGAR_USUARIOS_EXITO";
export const DESCARGA_USUARIOS_ERROR = "DESCARGA_USUARIOS_ERROR";