//Variables para inicio de sesion
export const COMENZAR_INICIO_LOGIN = "COMENZAR_INICIO_LOGIN";
export const INICIAR_SESION_EXITO = "INICIAR_SESION_EXITO";
export const INICIAR_SESION_ERROR = "INICIAR_SESION_ERROR";

//Consulta datos usuarios
export const COMENZAR_DESCARGA_USUARIOS = "COMENZAR_DESCARGA_USUARIOS";
export const DESCARGAR_USUARIOS_EXITO = "DESCARGAR_USUARIOS_EXITO";
export const DESCARGA_USUARIOS_ERROR = "DESCARGA_USUARIOS_ERROR";
//Consultar usuarios tipos maestro
export const COMENZAR_DESCARGA_MTRS = "COMENZAR_DESCARGA_MTRS";
export const DESCARGAR_MRTS_EXITO = "DESCARGAR_MRTS_EXITO";
export const DESCARGAR_MTRS_ERROR = "DESCARGAR_MTRS_ERROR";


//Obtener Proyectos generales
export const COMENZAR_DESCARGA_PROYECTOSG = "COMENZAR_DESCARGA_PROYECTOSG";
export const DESCARGAR_PROYECTOSG_EXITO = "DESCARGAR_PROYECTOSG_EXITO";
export const DESCARGA_PROYECTOSG_ERROR = "DESCARGA_PROYECTOSG_ERROR";
//Obtener Proyectos Maestro
export const OBTENER_PROYECTOS_MTRS = "OBTENER_PROYECTOS_MTRS";
export const OBTENER_PROYECTOS_MTRSEXITO = "OBTENER_PROYECTOS_MTRSEXITO";
export const OBTENER_PROYECTOS_MTRSERROR = "OBTENER_PROYECTOS_MTRSERROR";
//Eliminar proyectos 
export const ELIMINAR_PROYECTOS_MTRS = "ELIMINAR_PROYECTOS_MTRS";
export const ELIMINAR_PROYECTOS_MTRSEXITO = "ELIMINAR_PROYECTOS_MTRSEXITO";
export const ELIMINAR_PROYECTOS_MTRSERROR = "ELIMINAR_PROYECTOS_MTRSERROR";
//Actualizar proyectos
export const ACTUALIZAR_PROYECTOS_MTRS = "ACTUALIZAR_PROYECTOS_MTRS";
export const ACTUALIZAR_PROYECTOS_MTRSEXITO = "ACTUALIZAR_PROYECTOS_MTRSEXITO";
export const ACTUALIZAR_PROYECTOS_MTRSERROR = "ACTUALIZAR_PROYECTOS_MTRSERROR";
//Agregar proyectos
export const AGREGAR_PROYECTOS_MTRS = "AGREGAR_PROYECTOS_MTRS";
export const AGREGAR_PROYECTOS_MTRSEXITO = "AGREGAR_PROYECTOS_MTRSEXITO";
export const AGREGAR_PROYECTOS_MTRSERROR = "AGREGAR_PROYECTOS_MTRSERROR";




//VARIABLES SOLICITUDES

//Solicitudes maestros
export const OBTENER_SOLICITUDES_MTRS = "OBTENER_SOLICITUDES_MTRS";
export const OBTENER_SOLICITUDES_MTRSEXITO = "OBTENER_SOLICITUDES_MTRSEXITO";
export const OBTENER_SOLICITUDES_MTRSERROR = "OBTENER_SOLICITUDES_MTRSERROR";