//Variables para inicio de sesion
export const COMENZAR_INICIO_LOGIN = "COMENZAR_INICIO_LOGIN";
export const INICIAR_SESION_EXITO = "INICIAR_SESION_EXITO";
export const INICIAR_SESION_ERROR = "INICIAR_SESION_ERROR";
export const RENOVAR_SECCION_INICIADA = "RENOVAR_SECCION_INICIADA";
export const RENOVAR_SECCION_EXITO = "RENOVAR_SECCION_EXITO";
export const RENOVAR_SECCION_ERROR = "RENOVAR_SECCION_ERROR";
//Obtener datos del usuario global 
export const USUARIO_GLOBAL_COMENZAR = "USUARIO_GLOBAL_COMENZAR";
export const USUARIO_GLOBAL_EXITO = "USUARIO_GLOBAL_EXITO";
export const USUARIO_GLOBAL_ERROR = "USUARIO_GLOBAL_ERROR";



//Editar informacion usuario
export const ACTUALIZAR_USUARIO_COMENZAR = "ACTUALIZAR_USUARIO_COMENZAR";
export const ACTUALIZAR_USUARIO_EXITO = "ACTUALIZAR_USUARIO_EXITO";
export const ACTUALIZAR_USUARIO_ERROR = "ACTUALIZAR_USUARIO_ERROR";
//Editar informacion escolar
export const ACTUALIZAR_ESCOLAR_COMENZAR = "ACTUALIZAR_ESCOLAR_COMENZAR";
export const ACTUALIZAR_ESCOLAR_EXITO = "ACTUALIZAR_ESCOLAR_EXITO";
export const ACTUALIZAR_ESCOLAR_ERROR = "ACTUALIZAR_ESCOLAR_ERROR";
//Editar informacion proyectos
export const ACTUALIZAR_PROFESION_COMENZAR = "ACTUALIZAR_PROFESION_COMENZAR";
export const ACTUALIZAR_PROFESION_EXITO = "ACTUALIZAR_PROFESION_EXITO";
export const ACTUALIZAR_PROFESION_ERROR = "ACTUALIZAR_PROFESION_ERROR";




//Consulta datos usuarios
export const COMENZAR_DESCARGA_USUARIOS = "COMENZAR_DESCARGA_USUARIOS";
export const DESCARGAR_USUARIOS_EXITO = "DESCARGAR_USUARIOS_EXITO";
export const DESCARGA_USUARIOS_ERROR = "DESCARGA_USUARIOS_ERROR";
//Consultar usuarios tipos maestro
export const COMENZAR_DESCARGA_MTRS = "COMENZAR_DESCARGA_MTRS";
export const DESCARGAR_MRTS_EXITO = "DESCARGAR_MRTS_EXITO";
export const DESCARGAR_MTRS_ERROR = "DESCARGAR_MTRS_ERROR";
//Consultar descargar ususarios tipos alumno
export const COMENZAR_DESCARGA_ALUM = "COMENZAR_DESCARGA_ALUM";
export const DESCARGAR_ALUM_EXITO = "DESCARGAR_ALUM_EXITO";
export const DESCARGAR_ALUM_ERROR = "DESCARGAR_ALUM_ERROR";


//Obtener Proyectos generales
export const COMENZAR_DESCARGA_PROYECTOSG = "COMENZAR_DESCARGA_PROYECTOSG";
export const DESCARGAR_PROYECTOSG_EXITO = "DESCARGAR_PROYECTOSG_EXITO";
export const DESCARGA_PROYECTOSG_ERROR = "DESCARGA_PROYECTOSG_ERROR";
//Obtener Proyectos Maestro
export const OBTENER_PROYECTOS_MTRS = "OBTENER_PROYECTOS_MTRS";
export const OBTENER_PROYECTOS_MTRSEXITO = "OBTENER_PROYECTOS_MTRSEXITO";
export const OBTENER_PROYECTOS_MTRSERROR = "OBTENER_PROYECTOS_MTRSERROR";
//Eliminar proyectos 
export const ELIMINAR_PROYECTOS_MTRS = "ELIMINAR_PROYECTOS_MTRS";
export const ELIMINAR_PROYECTOS_MTRSEXITO = "ELIMINAR_PROYECTOS_MTRSEXITO";
export const ELIMINAR_PROYECTOS_MTRSERROR = "ELIMINAR_PROYECTOS_MTRSERROR";
//Actualizar proyectos
export const ACTUALIZAR_PROYECTOS_MTRS = "ACTUALIZAR_PROYECTOS_MTRS";
export const ACTUALIZAR_PROYECTOS_MTRSEXITO = "ACTUALIZAR_PROYECTOS_MTRSEXITO";
export const ACTUALIZAR_PROYECTOS_MTRSERROR = "ACTUALIZAR_PROYECTOS_MTRSERROR";
//Agregar proyectos
export const AGREGAR_PROYECTOS_MTRS = "AGREGAR_PROYECTOS_MTRS";
export const AGREGAR_PROYECTOS_MTRSEXITO = "AGREGAR_PROYECTOS_MTRSEXITO";
export const AGREGAR_PROYECTOS_MTRSERROR = "AGREGAR_PROYECTOS_MTRSERROR";




//VARIABLES SOLICITUDES

//Solicitudes maestros
export const OBTENER_SOLICITUDES_MTRS = "OBTENER_SOLICITUDES_MTRS";
export const OBTENER_SOLICITUDES_MTRSEXITO = "OBTENER_SOLICITUDES_MTRSEXITO";
export const OBTENER_SOLICITUDES_MTRSERROR = "OBTENER_SOLICITUDES_MTRSERROR";
//Actualizar solicitud del usario para maestro
export const ACEPTAR_SOLICITUD_ALUM = "ACEPTAR_SOLICITUD_ALUM";
export const ACEPTAR_SOLICITUD_ALUMEXITO = "ACEPTAR_SOLICITUD_ALUMEXITO";
export const ACEPTAR_SOLICITUD_ALUMERROR = "ACEPTAR_SOLICITUD_ALUMERROR";
//Rechazar solicitud y eliminarla 
export const ELIMINAR_SOLICITUD_ALUM = "ELIMINAR_SOLICITUD_ALUM";
export const ELIMINAR_SOLICITUD_ALUMEXITO = "ELIMINAR_SOLICITUD_ALUMEXITO";
export const ELIMINAR_SOLICITUD_ALUMERROR = "ELIMINAR_SOLICITUD_ALUMERROR";
//Enviar solicitud para un proyecto
export const SOLICITAR_SOLICITUD_ALUM = "ELIMINAR_SOLICITUD_ALUM";
export const SOLICITAR_SOLICITUD_ALUMEXITO = "ELIMINAR_SOLICITUD_ALUMEXITO";
export const SOLICITAR_SOLICITUD_ALUMERROR = "ELIMINAR_SOLICITUD_ALUMERROR";
//Solicitudes realizadas por el alumno
export const OBTENER_SOLICITUD_ALUM = "ELIMINAR_SOLICITUD_ALUM";
export const OBTENER_SOLICITUD_ALUMEXITO = "ELIMINAR_SOLICITUD_ALUMEXITO";
export const OBTENER_SOLICITUD_ALUMERROR = "ELIMINAR_SOLICITUD_ALUMERROR";